---
title: "Citation"
author: "Steffen Redeker"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  bookdown:pdf_document:
    toc: yes
    toc_depth: 3
bibliography: references1.bib
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(dplyr)
library(ggplot2)
library(gapminder)
library(stargazer)
library(bookdown)


```

# Title
This project was developed using the package *bookdown* by @bookdown.

This project was developed using the package *bookdown* by [@bookdown].

# Life expectancy and per capita GDP

```{r}
df_graph <- gapminder %>% 
  group_by(country) %>% 
  mutate(pcGDPgr = c(NA, diff(gdpPercap))/lag(gdpPercap) * 100,
         dlifeExp = c(NA, diff(lifeExp))) %>% 
  drop_na()
  
p <- ggplot(df_graph, aes(x = pcGDPgr,
                          y = dlifeExp)) + 
  geom_point(aes(color = continent)) + 
  geom_smooth(method = lm, se = FALSE) +
  scale_color_manual(values = continent_colors) + 
  theme_bw() + 
  themen(legend-position = "bottom" ) +
  labs(color = NULL,
       y = "Change in life expectancy",
       x = "Per capita GDP growth",
       caption = "Source: Gapminder.")
p
  

```

## Regression analysis

### Inclusion of dummy variables

```{r, results = 'asis'}

reg <- lm(dlifeExp ~ pcGDPgr, data = df_graph)

# Regression table
stargazer(reg,
          header = FALSE,
          type = "latex",
          label = "tab:regressions",
          title = "Relationship between per capita GDP growth and life expectancy, 1952-2007.",
          dep.var.labels = c("dlifeExp"),
          covariate.labels = c("pcGDPgr"),
          keep.stat = c("n", "rsq"))

```





\newpage

# References 



