---
title: "Lesson 9"
author: "Steffen Redeker"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output: 
  bookdown::pdf_document2:
    toc: true
    toc_depth: 2
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE,
                      warning = FALSE)

library(dplyr)
library(ggplot2)
library(gapminder)
library(stargazer)
library(kableExtra)

```

# the most populous countries in 2007

```{r}
pop_countries <- gapminder %>%
  filter(year == "2007") %>%
  group_by(continent) %>%
  select(country, pop) %>%
  arrange(desc(pop)) %>%
  slice(1:3) %>%
  ungroup()

pop_table <- pop_countries %>%
  select(country, pop) %>%
  kbl(booktabs = TRUE,
      caption = "The three most populous countries by continent in 2007. Source: Gapminder.",
      format.args = c(decimal.mark = ".",
                      big.mark = "\'"),
      col.names = c("Country", "Population")) %>%
  kable_styling(latex_options = c("hold_position")) %>%
  pack_rows("Africa, 1, 3") %>%
  pack_rows("Americas", 4, 7)
  

pop_table



```
# Life expectancy and per capita GDP
